//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTrader.Properties
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    var temp = new global::System.Resources.ResourceManager("FoxTrader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back
        {
            get
            {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Colour
        {
            get
            {
                return ResourceManager.GetString("Colour", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Game Options.
        /// </summary>
        internal static string GameOptions
        {
            get
            {
                return ResourceManager.GetString("GameOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FoxTrader™ V{0}.
        /// </summary>
        internal static string GameTrademark
        {
            get
            {
                return ResourceManager.GetString("GameTrademark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ico_FoxTrader
        {
            get
            {
                var obj = ResourceManager.GetObject("ico_FoxTrader", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language
        {
            get
            {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Load Game.
        /// </summary>
        internal static string LoadGame
        {
            get
            {
                return ResourceManager.GetString("LoadGame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        internal static string NewGame
        {
            get
            {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_FoxTrader_128x128
        {
            get
            {
                var obj = ResourceManager.GetObject("png_FoxTrader_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_FoxTrader_16x16
        {
            get
            {
                var obj = ResourceManager.GetObject("png_FoxTrader_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_FoxTrader_24x24
        {
            get
            {
                var obj = ResourceManager.GetObject("png_FoxTrader_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_FoxTrader_256x256
        {
            get
            {
                var obj = ResourceManager.GetObject("png_FoxTrader_256x256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_FoxTrader_32x32
        {
            get
            {
                var obj = ResourceManager.GetObject("png_FoxTrader_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_FoxTrader_48x48
        {
            get
            {
                var obj = ResourceManager.GetObject("png_FoxTrader_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_FoxTrader_512x512
        {
            get
            {
                var obj = ResourceManager.GetObject("png_FoxTrader_512x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_FoxTrader_64x64
        {
            get
            {
                var obj = ResourceManager.GetObject("png_FoxTrader_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_FoxTrader_96x96
        {
            get
            {
                var obj = ResourceManager.GetObject("png_FoxTrader_96x96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_FoxTraderSkin
        {
            get
            {
                var obj = ResourceManager.GetObject("png_FoxTraderSkin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string QuitGame
        {
            get
            {
                return ResourceManager.GetString("QuitGame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save Game.
        /// </summary>
        internal static string SaveGame
        {
            get
            {
                return ResourceManager.GetString("SaveGame", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ttf_chicago
        {
            get
            {
                var obj = ResourceManager.GetObject("ttf_chicago", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
